// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240708150502_primeiro-migration")]
    partial class primeiromigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Endereco = "Rua Sete de Setembro, 428",
                            Nome = "Roberto Marinho",
                            Telefone = "(16)99987-891"
                        },
                        new
                        {
                            Id = 2L,
                            Endereco = "Rua Tiradentes, 861",
                            Nome = "Juliana Oliveira",
                            Telefone = "(16)99357-5891"
                        },
                        new
                        {
                            Id = 3L,
                            Endereco = "Rua São Sebastião, 8176",
                            Nome = "Paulo Roberto",
                            Telefone = "(16)99927-9136"
                        },
                        new
                        {
                            Id = 4L,
                            Endereco = "Rua Bela Vista, 9948",
                            Nome = "Ana Maria",
                            Telefone = "(16)99741-9481"
                        });
                });

            modelBuilder.Entity("Model.Models.Emprestimo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdLivro")
                        .HasColumnType("bigint");

                    b.Property<string>("LivroTitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emprestimo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataRetirada = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 1L,
                            IdLivro = 4L,
                            LivroTitulo = "Verity",
                            NomeCliente = "Roberto Marinho"
                        },
                        new
                        {
                            Id = 2L,
                            DataDevolucao = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRetirada = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 1L,
                            IdLivro = 6L,
                            LivroTitulo = "Divergente",
                            NomeCliente = "Roberto Marinho"
                        },
                        new
                        {
                            Id = 3L,
                            DataRetirada = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 4L,
                            IdLivro = 2L,
                            LivroTitulo = "O nevoeiro",
                            NomeCliente = "Ana Maria"
                        },
                        new
                        {
                            Id = 4L,
                            DataDevolucao = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRetirada = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 3L,
                            IdLivro = 3L,
                            LivroTitulo = "Layla",
                            NomeCliente = "Paulo Roberto"
                        },
                        new
                        {
                            Id = 5L,
                            DataRetirada = new DateTime(2020, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 2L,
                            IdLivro = 5L,
                            LivroTitulo = "O cão dos Baskervilles",
                            NomeCliente = "Juliana Oliveira"
                        });
                });

            modelBuilder.Entity("Model.Models.Livro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Autor = "J. K. Rowling",
                            Capa = "",
                            Lancamento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Harry Potter e a pedra filosofal"
                        },
                        new
                        {
                            Id = 2L,
                            Autor = "Stephen King",
                            Capa = "",
                            Lancamento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "O nevoeiro"
                        },
                        new
                        {
                            Id = 3L,
                            Autor = "Colleen Hover",
                            Capa = "",
                            Lancamento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Layla"
                        },
                        new
                        {
                            Id = 4L,
                            Autor = "Collen Hover",
                            Capa = "",
                            Lancamento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Verity"
                        },
                        new
                        {
                            Id = 5L,
                            Autor = "Arthur Conan Doyle",
                            Capa = "",
                            Lancamento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "O cão dos Baskervilles"
                        },
                        new
                        {
                            Id = 6L,
                            Autor = "Patricia Cornwell",
                            Capa = "",
                            Lancamento = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Divergente"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
